/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
    export interface GlobalComponents {
        BareCodeReader: (typeof import("./src/components/BareCodeReader/bareCodeReader.vue"))["default"];
        HelloWorld: (typeof import("./src/components/HelloWorld.vue"))["default"];
        StockProductUpdate: (typeof import("./src/components/Stock_Product/StockProduct-Update.vue"))["default"];
    }
}
