/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddProduct: typeof import('./src/components/organisms/modals/AddProduct.vue')['default']
    BareCodeReader: typeof import('./src/components/BareCodeReader/bareCodeReader.vue')['default']
    FormAddProduct: (typeof import("./src/components/molecules/forms/FormAddProduct.vue"))["default"]
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ModalAddProduct: (typeof import("./src/components/organisms/modals/ModalAddProduct.vue"))["default"]
    'StockProduct.class': typeof import('./src/components/Stock_Product/StockProduct.class.vue')['default']
    StockProductUpdate: typeof import('./src/components/Stock_Product/StockProduct-Update.vue')['default']
  }
}
